// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/comments.proto

/*
Package comments is a generated protocol buffer package.

It is generated from these files:
	proto/comments.proto

It has these top-level messages:
	Comment
	Request
	Response
	SingleRequest
	WriteRequest
*/
package comments

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Comment struct {
	Id         string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	VideoId    string `protobuf:"bytes,2,opt,name=video_id,json=videoId" json:"video_id,omitempty"`
	DatePosted string `protobuf:"bytes,3,opt,name=date_posted,json=datePosted" json:"date_posted,omitempty"`
	User       string `protobuf:"bytes,4,opt,name=user" json:"user,omitempty"`
	Content    string `protobuf:"bytes,5,opt,name=content" json:"content,omitempty"`
	Likes      uint64 `protobuf:"varint,6,opt,name=likes" json:"likes,omitempty"`
	Dislikes   uint64 `protobuf:"varint,7,opt,name=dislikes" json:"dislikes,omitempty"`
}

func (m *Comment) Reset()                    { *m = Comment{} }
func (m *Comment) String() string            { return proto.CompactTextString(m) }
func (*Comment) ProtoMessage()               {}
func (*Comment) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Comment) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Comment) GetVideoId() string {
	if m != nil {
		return m.VideoId
	}
	return ""
}

func (m *Comment) GetDatePosted() string {
	if m != nil {
		return m.DatePosted
	}
	return ""
}

func (m *Comment) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

func (m *Comment) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *Comment) GetLikes() uint64 {
	if m != nil {
		return m.Likes
	}
	return 0
}

func (m *Comment) GetDislikes() uint64 {
	if m != nil {
		return m.Dislikes
	}
	return 0
}

type Request struct {
	VideoId string `protobuf:"bytes,1,opt,name=video_id,json=videoId" json:"video_id,omitempty"`
}

func (m *Request) Reset()                    { *m = Request{} }
func (m *Request) String() string            { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()               {}
func (*Request) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Request) GetVideoId() string {
	if m != nil {
		return m.VideoId
	}
	return ""
}

type Response struct {
	Comments []*Comment `protobuf:"bytes,1,rep,name=comments" json:"comments,omitempty"`
}

func (m *Response) Reset()                    { *m = Response{} }
func (m *Response) String() string            { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()               {}
func (*Response) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Response) GetComments() []*Comment {
	if m != nil {
		return m.Comments
	}
	return nil
}

type SingleRequest struct {
	CommentId string `protobuf:"bytes,1,opt,name=comment_id,json=commentId" json:"comment_id,omitempty"`
}

func (m *SingleRequest) Reset()                    { *m = SingleRequest{} }
func (m *SingleRequest) String() string            { return proto.CompactTextString(m) }
func (*SingleRequest) ProtoMessage()               {}
func (*SingleRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *SingleRequest) GetCommentId() string {
	if m != nil {
		return m.CommentId
	}
	return ""
}

type WriteRequest struct {
	VideoId string `protobuf:"bytes,1,opt,name=video_id,json=videoId" json:"video_id,omitempty"`
	User    string `protobuf:"bytes,2,opt,name=user" json:"user,omitempty"`
	Content string `protobuf:"bytes,3,opt,name=content" json:"content,omitempty"`
}

func (m *WriteRequest) Reset()                    { *m = WriteRequest{} }
func (m *WriteRequest) String() string            { return proto.CompactTextString(m) }
func (*WriteRequest) ProtoMessage()               {}
func (*WriteRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *WriteRequest) GetVideoId() string {
	if m != nil {
		return m.VideoId
	}
	return ""
}

func (m *WriteRequest) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

func (m *WriteRequest) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func init() {
	proto.RegisterType((*Comment)(nil), "comments.Comment")
	proto.RegisterType((*Request)(nil), "comments.Request")
	proto.RegisterType((*Response)(nil), "comments.Response")
	proto.RegisterType((*SingleRequest)(nil), "comments.SingleRequest")
	proto.RegisterType((*WriteRequest)(nil), "comments.WriteRequest")
}

func init() { proto.RegisterFile("proto/comments.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 329 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x52, 0x4d, 0x4b, 0x03, 0x31,
	0x14, 0x6c, 0xb6, 0x1f, 0xbb, 0x7d, 0x55, 0xd1, 0x47, 0xd1, 0x58, 0x10, 0xcb, 0xe2, 0xa1, 0x17,
	0x2b, 0x54, 0x2f, 0xc5, 0x93, 0x08, 0x96, 0xde, 0x64, 0x05, 0x7b, 0x2c, 0xda, 0x3c, 0x24, 0xb8,
	0xdd, 0xd4, 0x4d, 0xea, 0x3f, 0x13, 0xfc, 0x79, 0x62, 0x92, 0xee, 0x76, 0xb1, 0xe0, 0x2d, 0x33,
	0x93, 0xbc, 0x37, 0x33, 0x04, 0xba, 0xab, 0x5c, 0x19, 0x75, 0xb5, 0x50, 0xcb, 0x25, 0x65, 0x46,
	0x0f, 0x2d, 0xc4, 0x68, 0x83, 0xe3, 0x2f, 0x06, 0xe1, 0xbd, 0x03, 0x78, 0x00, 0x81, 0x14, 0x9c,
	0xf5, 0xd9, 0xa0, 0x9d, 0x04, 0x52, 0xe0, 0x29, 0x44, 0x9f, 0x52, 0x90, 0x9a, 0x4b, 0xc1, 0x03,
	0xcb, 0x86, 0x16, 0x4f, 0x05, 0x9e, 0x43, 0x47, 0xbc, 0x18, 0x9a, 0xaf, 0x94, 0x36, 0x24, 0x78,
	0xdd, 0xaa, 0xf0, 0x4b, 0x3d, 0x5a, 0x06, 0x11, 0x1a, 0x6b, 0x4d, 0x39, 0x6f, 0x58, 0xc5, 0x9e,
	0x91, 0x43, 0xb8, 0x50, 0x99, 0xa1, 0xcc, 0xf0, 0xa6, 0x1b, 0xe7, 0x21, 0x76, 0xa1, 0x99, 0xca,
	0x77, 0xd2, 0xbc, 0xd5, 0x67, 0x83, 0x46, 0xe2, 0x00, 0xf6, 0x20, 0x12, 0x52, 0x3b, 0x21, 0xb4,
	0x42, 0x81, 0xe3, 0x0b, 0x08, 0x13, 0xfa, 0x58, 0x93, 0x36, 0x15, 0x9b, 0xac, 0x62, 0x33, 0x1e,
	0x43, 0x94, 0x90, 0x5e, 0xa9, 0x4c, 0x13, 0x5e, 0x42, 0x91, 0x9a, 0xb3, 0x7e, 0x7d, 0xd0, 0x19,
	0x1d, 0x0d, 0x8b, 0x5a, 0x7c, 0x05, 0x49, 0x59, 0xcc, 0x10, 0xf6, 0x9f, 0x64, 0xf6, 0x96, 0xd2,
	0x66, 0xcd, 0x19, 0x80, 0x17, 0xcb, 0x45, 0x6d, 0xcf, 0x4c, 0x45, 0x3c, 0x83, 0xbd, 0x59, 0x2e,
	0x0d, 0xfd, 0xef, 0xaa, 0xe8, 0x26, 0xd8, 0xdd, 0x4d, 0xbd, 0xd2, 0xcd, 0xe8, 0x9b, 0x41, 0xe4,
	0xed, 0x69, 0xbc, 0x85, 0xc3, 0x09, 0x99, 0xbb, 0x34, 0x7d, 0x50, 0xf9, 0xb3, 0x1f, 0xb7, 0x15,
	0xc3, 0x2f, 0xef, 0xe1, 0x36, 0xe5, 0xf2, 0xc7, 0x35, 0x1c, 0x43, 0x7b, 0x42, 0xc6, 0xa5, 0xc2,
	0x93, 0xf2, 0x4a, 0x25, 0x67, 0xef, 0x6f, 0x2b, 0x71, 0x0d, 0x6f, 0xa0, 0x69, 0xd3, 0xe1, 0x71,
	0xa9, 0x6e, 0xc7, 0xdd, 0xf9, 0xea, 0xb5, 0x65, 0x7f, 0xdb, 0xf5, 0x4f, 0x00, 0x00, 0x00, 0xff,
	0xff, 0x3f, 0xe6, 0x59, 0x96, 0x85, 0x02, 0x00, 0x00,
}
